### ISSUE TITLE
app is just crashing

### ISSUE THREAD

**Issue by KiranPranay** [adnan0786/Animated_Bottom_Navigation_Bar_Android#1]
here's the crash url
https://del.dog/morobanang

**Comment by adnan0786** [comment]
Show me your activity where you replacing the fragments

**Comment by KiranPranay** [comment]
i had written exactly what you did , please take a look .
[activity_files.txt](https://github.com/adnan0786/Animated_Bottom_Navigation_Bar_Android/files/5107316/activity_files.txt)

**Comment by adnan0786** [comment]
[
[activity_files.txt](https://github.com/adnan0786/Animated_Bottom_Navigation_Bar_Android/files/5107400/activity_files.txt)
](url)


i edit the activity_files.txt check it out and also add the dependcies that i mentioned in file use them in app level gradle file

**Comment by KiranPranay** [comment]
Really, Very Thank You for your response.

it worked for me, but now am unable switch fragments.
If possible please check the files below.
THANK YOU.
[fragments-java.txt](https://github.com/adnan0786/Animated_Bottom_Navigation_Bar_Android/files/5107673/fragments-java.txt)
[fragments-xml's.txt](https://github.com/adnan0786/Animated_Bottom_Navigation_Bar_Android/files/5107674/fragments-xml.s.txt)
[main-activity-xml-java.txt](https://github.com/adnan0786/Animated_Bottom_Navigation_Bar_Android/files/5107675/main-activity-xml-java.txt)

**Comment by adnan0786** [comment]
all code is written in that file used it 
wellcom

**Comment by adnan0786** [comment]
if you got the point then kindly close or solved this issue.

**Comment by KiranPranay** [comment]
> 
> 
> all code is written in that file used it
> wellcom

didn't get  that, will eloborate you  please .

**Comment by adnan0786** [comment]
> > all code is written in that file used it
> > wellcom
> 
> didn't get that, will eloborate you please .

All the is written in text file as well as in MainActivity.class go and use it

**Comment by KiranPranay** [comment]
> 
> 
> [
> [activity_files.txt](https://github.com/adnan0786/Animated_Bottom_Navigation_Bar_Android/files/5107400/activity_files.txt)
> ](url)
> 
> i edit the activity_files.txt check it out and also add the dependcies that i mentioned in file use them in app level gradle file

you mean this ?

**Comment by adnan0786** [comment]
if you are still facing any issue clone this repository in android studio 
and if you don't know how to clone check any tutorial on youtube
Thanks

**Comment by KiranPranay** [comment]
> 
> 
> if you are still facing any issue clone this repository in android studio
> and if you don't know how to clone check any tutorial on youtube
> Thanks

thank you for your response , i will try It.
the only problem i facing is switching fragments, may be cloning will be better .
